language: node_js
node_js:
  - 6
  - 8
  - 9
script: npm run-script test-travis
after_script: cat ./coverage/lcov.info | coveralls

notifications:
  email: false
  slack:
    rooms:
      - secure: Il+TTS4jB8nFoxiEddQ7AEGC6h0wNKsaTQU2WixaxU58zmh7jYQg1nq9orrlzwDFXmUabBKJA6e+hhiJ47cOcLCDb5sb4Hp34YwKxZ3CICKsbPOxHvkjz+zEUU/46ZJbojfPfhj8bb8+e40XSaivv1ZiRiR3uuri24u5fV6VEVo=
    on_success: always
    on_failure: always
